default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: aili
  password: G00d80y3nd3r
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: henslowe5_development

test:
  <<: *default
  database: henslowe5_test

#
production:
  <<: *default
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
