# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 94535402983357ee58f1f568196c6e26f2a3bf26ec5015983702d41f82f3516bc13ed0b7367b224136eb0f421a5fbe0b6c0b09eb1f41c0d1cf8611947dbe27e8

test:
  secret_key_base: 24e6e1d72f1b6f4166be48e0daa63a1da0d56b0c3a11031bf502766699e4ec92f30636a7408da1430a0e71f2b9387e82486689b371ffea81a09c7f774a8bae48

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
